<a href="https://colab.research.google.com/github/VineetSivadasan/houses/blob/main/Use_case_GB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import matplotlib.image as mpimg
  
  from scipy.stats import multivariate_normal as mvn
  
  %matplotlib inline
  df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_train.csv')
  df.head()

Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       5  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       0  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       4  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       1  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       9  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [4]:
df.shape

(60000, 787)

In [5]:
df_array = df.to_numpy() #turn the training dataset into an array
df_array

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [6]:
print_NaN_rows = df[df.isnull().any(axis=1)] #list the rows where NaN appears
print_NaN_rows

Empty DataFrame
Columns: [Unnamed: 0, index, labels, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 787 columns]

In [7]:
print_None_rows = df[df.eq("None").any(axis=1)]  #check to see if there are any 'None' values in any row
print_NaN_rows.shape

(0, 787)

In [8]:
y = df_array[:,2] #extract the label column
y

array([5, 0, 4, ..., 5, 6, 8])

In [9]:
y.shape

(60000,)

In [10]:
X = np.delete(df_array, [0,1,2], axis=1)

In [11]:
X_normalised = X/255 

In [12]:
class GaussBayes():

  def fit(self, X, y, epsilon):
    self.likelihoods =dict()
    self.priors = dict()

    self.K = set(y.astype(int))

    for k in self.K:
      X_k = X[y==k,:]
      N_k, D = X_k.shape
      mu_k = X_k.mean(axis=0)
      self.likelihoods[k] ={"mean":X_k.mean(axis=0),"cov":(1/(N_k-1))*np.matmul((X_k-mu_k).T,X_k-mu_k)+ epsilon*np.identity(D)}
      self.priors[k] = len(X_k)/len(X)


  def predict(self, X):
    N, D = X.shape

    P_hat = np.zeros((N,len(self.K)))

    for k, l in self.likelihoods.items():
      P_hat[:,k] = mvn.logpdf(X,l["mean"],l["cov"]) + np.log(self.priors[k])
    return P_hat.argmax(axis=1)

In [13]:
gbayes= GaussBayes()

In [15]:
def accuracy_training_GB(y,y_hat_training_gbayes):
  return np.mean(y== y_hat_training_gbayes)

result_gbayes_training = []
iteration = []

for i in np.arange(0.001,0.4,0.001):
  gbayes.fit(X_normalised,y,i)
  y_hat_training_gbayes=gbayes.predict(X_normalised)
  accuracy = accuracy_training_GB(y,y_hat_training_gbayes) #training accuracy
  result_gbayes_training.append(accuracy)
  iteration.append(i)
  print("i =", i, "accuracy =", accuracy) #training accuracy
result_GB_df = pd.DataFrame(result_gbayes_training)
iteration_df = pd.DataFrame(iteration)
result_GNB_df.to_csv('result_gbayes_train.csv')
iteration_df.to_csv('iteration_gbayes_train.csv')

i = 0.001 accuracy = 0.9306333333333333
i = 0.002 accuracy = 0.9397166666666666
i = 0.003 accuracy = 0.9448166666666666
i = 0.004 accuracy = 0.9478833333333333
i = 0.005 accuracy = 0.9500333333333333
i = 0.006 accuracy = 0.9515
i = 0.007 accuracy = 0.9529666666666666
i = 0.008 accuracy = 0.9541166666666666
i = 0.009000000000000001 accuracy = 0.9550166666666666
i = 0.010000000000000002 accuracy = 0.9555333333333333
i = 0.011 accuracy = 0.9561
i = 0.012 accuracy = 0.9567
i = 0.013000000000000001 accuracy = 0.9571333333333333
i = 0.014000000000000002 accuracy = 0.9574666666666667
i = 0.015 accuracy = 0.9579166666666666
i = 0.016 accuracy = 0.9582166666666667
i = 0.017 accuracy = 0.9583333333333334
i = 0.018000000000000002 accuracy = 0.9585666666666667
i = 0.019000000000000003 accuracy = 0.9588166666666667
i = 0.02 accuracy = 0.9589666666666666
i = 0.021 accuracy = 0.95915
i = 0.022000000000000002 accuracy = 0.9592166666666667
i = 0.023 accuracy = 0.9591666666666666
i = 0.024 accuracy = 0.

KeyboardInterrupt: ignored

In [17]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_test.csv')
df_test.head()

Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       7  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       2  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       1  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       0  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       4  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [18]:
df_test.shape

(10000, 787)

In [19]:
df_test_array = df_test.to_numpy()
df_test_array

array([[   0,    0,    7, ...,    0,    0,    0],
       [   1,    1,    2, ...,    0,    0,    0],
       [   2,    2,    1, ...,    0,    0,    0],
       ...,
       [9997, 9997,    4, ...,    0,    0,    0],
       [9998, 9998,    5, ...,    0,    0,    0],
       [9999, 9999,    6, ...,    0,    0,    0]])

In [20]:
y_test = df_test_array[:,2] #extract the label column
y_test

array([7, 2, 1, ..., 4, 5, 6])

In [21]:
X_test = np.delete(df_test_array, [0,1,2], axis=1)

In [22]:
X_test_normalised = X_test/255   #double slash to produce integer values instead of float

In [24]:
y_hat_test_GB=gbayes.predict(X_test_normalised)

In [26]:
def accuracy_test_gbayes(y_test,y_hat_test_GB):
  return np.mean(y_test== y_hat_test_GB)


result_gbayes_test = []
iteration = []

for i in np.arange(0.001,0.4,0.001):
  gbayes.fit(X_normalised,y,i)
  y_hat_test_gbayes=gbayes.predict(X_test_normalised)
  accuracy = accuracy_test_gbayes(y_test,y_hat_test_gbayes) #training accuracy
  result_gbayes_test.append(accuracy)
  iteration.append(i)
  print("i =", i, "accuracy =", accuracy) #training accuracy
result_GB_test_df = pd.DataFrame(result_gbayes_test)
iteration_df = pd.DataFrame(iteration)
result_GB_test_df.to_csv('result_gbayes_train.csv')
iteration_df.to_csv('iteration_gbayes_train.csv')

i = 0.001 accuracy = 0.9108
i = 0.002 accuracy = 0.924
i = 0.003 accuracy = 0.9307
i = 0.004 accuracy = 0.9355
i = 0.005 accuracy = 0.9381
i = 0.006 accuracy = 0.9403
i = 0.007 accuracy = 0.9423
i = 0.008 accuracy = 0.9444
i = 0.009000000000000001 accuracy = 0.9461
i = 0.010000000000000002 accuracy = 0.9473
i = 0.011 accuracy = 0.9485
i = 0.012 accuracy = 0.9494
i = 0.013000000000000001 accuracy = 0.9498
i = 0.014000000000000002 accuracy = 0.9508
i = 0.015 accuracy = 0.951
i = 0.016 accuracy = 0.9516
i = 0.017 accuracy = 0.952
i = 0.018000000000000002 accuracy = 0.9526
i = 0.019000000000000003 accuracy = 0.953
i = 0.02 accuracy = 0.9534
i = 0.021 accuracy = 0.954
i = 0.022000000000000002 accuracy = 0.9546
i = 0.023 accuracy = 0.9549
i = 0.024 accuracy = 0.9553
i = 0.025 accuracy = 0.9556
i = 0.026000000000000002 accuracy = 0.9559
i = 0.027000000000000003 accuracy = 0.9559
i = 0.028 accuracy = 0.956
i = 0.029 accuracy = 0.9559
i = 0.030000000000000002 accuracy = 0.9564
i = 0.031 accurac