<a href="https://colab.research.google.com/github/VineetSivadasan/houses/blob/main/Use_case_GNB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  import numpy as np
  import pandas as pd
  import matplotlib.pyplot as plt
  import matplotlib.image as mpimg
  
  from scipy.stats import multivariate_normal as mvn
  
  %matplotlib inline
  df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_train.csv')
  df.head()

Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       5  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       0  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       4  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       1  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       9  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [ ]:
df.shape

(60000, 787)

In [ ]:
df_array = df.to_numpy() #turn the training dataset into an array
df_array

array([[    0,     0,     5, ...,     0,     0,     0],
       [    1,     1,     0, ...,     0,     0,     0],
       [    2,     2,     4, ...,     0,     0,     0],
       ...,
       [59997, 59997,     5, ...,     0,     0,     0],
       [59998, 59998,     6, ...,     0,     0,     0],
       [59999, 59999,     8, ...,     0,     0,     0]])

In [ ]:
print_NaN_rows = df[df.isnull().any(axis=1)] #list the rows where NaN appears
print_NaN_rows

Empty DataFrame
Columns: [Unnamed: 0, index, labels, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 787 columns]

In [ ]:
print_None_rows = df[df.eq("None").any(axis=1)]  #check to see if there are any 'None' values in any row
print_NaN_rows.shape

(0, 787)

In [ ]:
y = df_array[:,2] #extract the label column
y

array([5, 0, 4, ..., 5, 6, 8])

In [ ]:
y.shape

(60000,)

In [ ]:
X = np.delete(df_array, [0,1,2], axis=1)

In [ ]:
X_normalised = X/255 

In [ ]:
#using Naive_Bayes
class GaussNB():

  def fit(self, X,y, epsilon):
    self.likelihoods = dict()
    self.priors = dict()

    self.K = set(y.astype(int))

    for k in self.K:
      X_k = X[y==k,:]
      self.likelihoods[k] = {"mean":X_k.mean(axis=0), "cov":X_k.var(axis=0) + epsilon}
      self.priors[k]= len(X_k)/len(X)
  

  def predict(self, X):
    N, D = X.shape

    P_hat = np.zeros((N,len(self.K)))

    for k, l in self.likelihoods.items():
      P_hat[:,k] = mvn.logpdf(X, l["mean"], l["cov"]) + np.log(self.priors[k])
    
    return P_hat.argmax(axis=1)

In [ ]:
gnb = GaussNB()

In [ ]:
def accuracy_training_GNB(y,y_hat_training_GNB):
  return np.mean(y== y_hat_training_GNB)

result_GNB_training = []
iteration = []

for i in np.arange(0.001,0.5,0.001):
  gnb.fit(X_normalised,y,i)
  y_hat_training_GNB=gnb.predict(X_normalised)
  accuracy = accuracy_training_GNB(y,y_hat_training_GNB)
  result_GNB_training.append(accuracy) 
  iteration.append(i)
  print("i =", i, "accuracy =", accuracy) #training accuracy
result_GNB_df = pd.DataFrame(result_GNB_training)
iteration_df = pd.DataFrame(iteration)
result_GNB_df.to_csv('result_gnb_train.csv')
iteration_df.to_csv('iteration_train.csv')


i = 0.001 accuracy = 0.7682333333333333
i = 0.002 accuracy = 0.78075
i = 0.003 accuracy = 0.7874333333333333
i = 0.004 accuracy = 0.7915166666666666
i = 0.005 accuracy = 0.7947
i = 0.006 accuracy = 0.7969
i = 0.007 accuracy = 0.7988333333333333
i = 0.008 accuracy = 0.7999
i = 0.009000000000000001 accuracy = 0.8010166666666667
i = 0.010000000000000002 accuracy = 0.8015833333333333
i = 0.011 accuracy = 0.8020166666666667
i = 0.012 accuracy = 0.8022333333333334
i = 0.013000000000000001 accuracy = 0.8023166666666667
i = 0.014000000000000002 accuracy = 0.8022
i = 0.015 accuracy = 0.8024666666666667
i = 0.016 accuracy = 0.8023666666666667
i = 0.017 accuracy = 0.80205
i = 0.018000000000000002 accuracy = 0.8016833333333333
i = 0.019000000000000003 accuracy = 0.8016
i = 0.02 accuracy = 0.8012833333333333
i = 0.021 accuracy = 0.80105
i = 0.022000000000000002 accuracy = 0.8007333333333333
i = 0.023 accuracy = 0.8007166666666666
i = 0.024 accuracy = 0.8005333333333333
i = 0.025 accuracy = 0.800183

0.8022

In [ ]:
df_test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/MNIST_test.csv')
df_test.head()

Unnamed: 0  index  labels  0  1  2  3  ...  777  778  779  780  781  782  783
0           0      0       7  0  0  0  0  ...    0    0    0    0    0    0    0
1           1      1       2  0  0  0  0  ...    0    0    0    0    0    0    0
2           2      2       1  0  0  0  0  ...    0    0    0    0    0    0    0
3           3      3       0  0  0  0  0  ...    0    0    0    0    0    0    0
4           4      4       4  0  0  0  0  ...    0    0    0    0    0    0    0

[5 rows x 787 columns]

In [ ]:
df_test.shape

(10000, 787)

In [ ]:
df_test_array = df_test.to_numpy()
df_test_array

array([[   0,    0,    7, ...,    0,    0,    0],
       [   1,    1,    2, ...,    0,    0,    0],
       [   2,    2,    1, ...,    0,    0,    0],
       ...,
       [9997, 9997,    4, ...,    0,    0,    0],
       [9998, 9998,    5, ...,    0,    0,    0],
       [9999, 9999,    6, ...,    0,    0,    0]])

In [ ]:
print_NaN_rows = df_test[df_test.isnull().any(axis=1)] #list the rows where NaN appears
print_NaN_rows

Empty DataFrame
Columns: [Unnamed: 0, index, labels, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, ...]
Index: []

[0 rows x 787 columns]

In [ ]:
print_None_rows = df_test[df_test.eq("None").any(axis=1)]  #check to see if there are any 'None' values in any row
print_NaN_rows.shape

(0, 787)

In [ ]:
y_test = df_test_array[:,2] #extract the label column
y_test

array([7, 2, 1, ..., 4, 5, 6])

In [ ]:
X_test = np.delete(df_test_array, [0,1,2], axis=1)

In [ ]:
X_test.shape

(10000, 784)

In [ ]:
X_test_normalised = X_test/255   #double slash to produce integer values instead of float

In [ ]:
def accuracy_test_GNB(y_test,y_hat_test_GNB):
  return np.mean(y_test== y_hat_test_GNB)


result_GNB_test = []
iteration = []

for i in np.arange(0.001,0.5,0.001):
  gnb.fit(X_normalised,y,i)
  y_hat_test_GNB=gnb.predict(X_test_normalised)
  accuracy = accuracy_test_GNB(y_test,y_hat_test_GNB)
  result_GNB_test.append(accuracy) 
  iteration.append(i)
  print("i =", i, "accuracy =", accuracy) #training accuracy
result_GNB_test_df = pd.DataFrame(result_GNB_test)
iteration_df = pd.DataFrame(iteration)
result_GNB_test_df.to_csv('result_gnb_test.csv')
iteration_df.to_csv('iteration_test.csv')

i = 0.001 accuracy = 0.7746
i = 0.002 accuracy = 0.7904
i = 0.003 accuracy = 0.7984
i = 0.004 accuracy = 0.8041
i = 0.005 accuracy = 0.8051
i = 0.006 accuracy = 0.8062
i = 0.007 accuracy = 0.8084
i = 0.008 accuracy = 0.8107
i = 0.009000000000000001 accuracy = 0.8118
i = 0.010000000000000002 accuracy = 0.8141
i = 0.011 accuracy = 0.8146
i = 0.012 accuracy = 0.8143
i = 0.013000000000000001 accuracy = 0.8145
i = 0.014000000000000002 accuracy = 0.8146
i = 0.015 accuracy = 0.8146
i = 0.016 accuracy = 0.8154
i = 0.017 accuracy = 0.8147
i = 0.018000000000000002 accuracy = 0.8139
i = 0.019000000000000003 accuracy = 0.8144
i = 0.02 accuracy = 0.8141
i = 0.021 accuracy = 0.8139
i = 0.022000000000000002 accuracy = 0.8138
i = 0.023 accuracy = 0.813
i = 0.024 accuracy = 0.8131
i = 0.025 accuracy = 0.8131
i = 0.026000000000000002 accuracy = 0.8133
i = 0.027000000000000003 accuracy = 0.8134
i = 0.028 accuracy = 0.8124
i = 0.029 accuracy = 0.8121
i = 0.030000000000000002 accuracy = 0.8118
i = 0.031 ac

In [ ]:
prescription = mpimg.imread('/content/drive/MyDrive/Colab Notebooks/prescription.jpg')
prescription

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [ ]:
prescription.shape

(774, 800, 3)